ERP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.schemas.coreapi import AutoSchema

from rest_framework.routers import DefaultRouter

from rest_framework import routers

router = DefaultRouter()
from rest_framework.schemas.coreapi import AutoSchema

urlpatterns = [
    path('admin/', admin.site.urls),
 
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls")) ,            # UI Kits Html files

    #Customer URL COnfig
    # path("customer/",include('customer.urls')),
    path('customer/',include('customer.urls',namespace="customer")),
    path('product/',include('product.urls',namespace="product")),
    path('sale/',include('sale.urls',namespace="sale")),
    path('inventory/',include('inventory.urls',namespace="inventory")),
    path('purchase/',include('purchase.urls',namespace="purchase")),
    path('invoice/',include('invoice.urls',namespace="invoice")),
    path('ie/',include('imp_exp.urls',namespace="imp-exp")),

    #ALL-API
    path('api/',include('api.urls',namespace="api")),

    #REST FRAMEWORK
    #Add later
    # path(r'api/', include('rest_framework.urls', namespace='rest_framework')),
    # path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
    # path(r'', include(router.urls)),

    #OPENAPIdocs
    path('docs/',include_docs_urls(title="ERP API")),
    path('schema/', get_schema_view(
        title="ERP API LIST",
        description="API for all things …",
        version="1.0.0"
     ), name='openapi-schema'),




    #frontend
    path('frontend/',include('frontend.urls',namespace="frontend")),





     

   
  




    




    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path,include
from django.contrib.auth.decorators import login_required

from .views import (
    IndexView,
    GetCategoryRelatedProduct,
    ProductListView,
    ProductDetail,
    AddtoCart,
    BuyProduct,
    ViewAddtoCartItem,
    UpdateCart,
    RemovefromCart,
    CheckoutView,
    SearchView,
    VendorDetailView,
    AddCoupon,
    htmx_test_view,
    rating_test
   
)

app_name="frontend"

urlpatterns = [
    path("", IndexView, name="frontend"),
    path("category/<int:category>/", GetCategoryRelatedProduct, name="category-related-product"),
    path('product-list',ProductListView,name="p-list"),
    path('product/<int:product>/',ProductDetail,name="p-detail"),
    path('add-to-cart/<int:product>/',AddtoCart,name="add-to-cart"),
    path('buy-product/<int:product>/',BuyProduct,name="buy-product"), #create so and qty update
    path('cart/',ViewAddtoCartItem,name="view-cart"),
    path('update-cart/',UpdateCart,name="update-cart"),
    path('removefromcart/<int:product>/',RemovefromCart,name="remove-from-cart"),
    path('checkout/',CheckoutView.as_view(),name="checkout-view"),
    path('search/',SearchView,name="search-view"),
    path('vendor/<int:id>/',VendorDetailView.as_view(),name="vendor-detail"),
    path('add-coupon',AddCoupon,name="add-coupon-view"),
    path('test/',htmx_test_view,name="htmx-test"),
    path('rating/',rating_test,name='rating-test')

    

   














    


   

    
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_zip = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    # payment_option = forms.ChoiceField(
    #     widget=forms.RadioSelect(attrs={
    #         'class':'custom-control-input',
    #     }), choices=PAYMENT_CHOICES)

    def __init__(self,*args, **kwargs):
        super(CheckoutForm,self).__init__(*args, **kwargs)

        for i in self.fields:
            self.fields[i].widget.attrs.update({'class':'form-control'})
        
       
       


class CouponForm(forms.Form):
    
    code = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Promo Code',
        'class':'form-control',
        'aria-label':"Recipient's username",
        'aria-describedby':'basic-addon2'

    }))

frontend/views.py
from curses.ascii import HT
from http.client import HTTPResponse
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http import JsonResponse,HttpResponse
from django.shortcuts import redirect, render
from django.utils import tree
from product.models import Product,ProductCategory
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from customer.models import Addr, Customer
from sale.models import SaleOrder,SaleOrderLine,Coupon
import datetime
#method for creating ref number 
from sale.views import  create_so_num
# Create your views here.
import json 
from django.views.generic import View
from frontend.forms import CheckoutForm
# from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from product.models import PRODUCT_COLORS,PRODUCT_RATINGS


def IndexView(request):
    product_lists = Product.objects.all()
    vendor_lists = Customer.objects.filter(is_vendor=True)
    context = {
        "product_lists": product_lists,
        "vendor_lists":vendor_lists
       
    }
    return render(request,"user-frontend/user-ui/index.html",context)


def ProductListView(request):
    product_lists = Product.objects.all()
    context = {
        "product_lists":product_lists
    }

    return render(request,"user-frontend/user-ui/product-list.html",context)

def GetCategoryRelatedProduct(request,category):
    category_lists = ProductCategory.objects.all()[:5]

    try:
        category_obj =  ProductCategory.objects.get(id = category)
    except ObjectDoesNotExist:
        return HttpResponse("Not related category found")
    
    product_lists = Product.objects.filter(category=category_obj)

    context = {
        "product_lists":product_lists,
        "category_lists":category_lists
    }

    return render(request,"user-frontend/user-ui/category_base_product_list.html",context)


    # product_lists = Product.objects.all()
    # data = {
    #     "name":product_lists[0].name,
    #     "category":product_lists[0].category.name,
    #     "image":product_lists[0].image.url,
    #     "slug":product_lists[0].slug
    #     # "name":product_lists[0].name,


    # }
    # return JsonResponse(data)


def ProductDetail(request,product):

    product_obj = get_object_or_404(Product, pk=product)
    product_lists = Product.objects.exclude(id=product)[:3]
    context = {
        "product":product_obj,
        "product_lists":product_lists,
    }

    return render(request,"user-frontend/user-ui/product_detail.html",context)


# @login_required
def AddtoCart(request,product):


    if not request.user.is_authenticated:
        return JsonResponse({"error":"Login First"})
 
    return JsonResponse({"data":"Add to Cart Called"})


def BuyProduct(request,product):

   

    if not request.user.is_authenticated:
        return JsonResponse({"error":"Login First"})
 
    product_id = request.POST.get('productid')
    qty = request.POST.get('quantity')
    qty = int(qty)

    
    product_id = int(product_id)

    product_obj = Product.objects.get(id=product_id)


    user_obj = request.user
    try:
        customer_obj = Customer.objects.get(user=user_obj)
    except:
        return JsonResponse({"error":"Not a Customer"})
    # so_obj = SaleOrder.objects.get_or_create(customer=customer_obj,order_date=datetime.datetime.today())
    #filter by customer n status, not by date, if SO need to crete order date, so passing just 
    # https://stackoverflow.com/questions/13610896/django-get-or-create-how-to-say-commit-false
    defaults = {'order_date': datetime.datetime.today()}
    so_obj = SaleOrder.objects.get_or_create(customer=customer_obj,status='q',defaults=defaults)

    so_obj = so_obj[0]
    so_obj.ref = create_so_num()
    so_obj.save()
   
    

    so_line_obj = SaleOrderLine.objects.filter(sale_order=so_obj,product=product_obj)
    print(so_line_obj)
    if so_line_obj.exists():
        so_line_obj= so_line_obj[0]
        # so_line_obj.quantity += qty
        # so_line_obj.sub_total = so_line_obj.get_subtotal()

        # so_line_obj.save()

        # #update the sale order total price in Sale order object
        # so_obj = so_line_obj.sale_order
        # so_obj.total_price = so_obj.sale_order_total()
        # so_obj.save()
        qty_updated = so_line_obj.quantity +  qty
        so_line_obj.add_to_cart_update_qty_and_subtotal_so_price(qty=qty_updated)
        return JsonResponse({"data":"Qty Updated"})
    else:
        so_line_obj = SaleOrderLine.objects.create(sale_order=so_obj,product=product_obj,quantity=qty)
        so_line_obj.add_to_cart_update_qty_and_subtotal_so_price(qty=qty)
        
        
        # so_line_obj.sub_total = so_line_obj.get_subtotal()
        # so_line_obj.save()

        # #update the sale order total price in Sale order object
        
        # so_obj = so_line_obj.sale_order
        # so_obj.total_price = so_obj.sale_order_total()
        # so_obj.save()


        

        #updating on the cart Navbar Count,So i return count to the client

         



    return JsonResponse({"data":"created","count":1})


def ViewAddtoCartItem(request):

    return render(request,"user-frontend/user-ui/view_add_to_cart.html")




def UpdateCart(request):
    #products getting from ajax is JSON STRINGFY, so need to change python object
    product_and_qty_json_lists = request.POST['products']
    product_n_qty_dict = json.loads(product_and_qty_json_lists)

    user_obj = request.user
    try:
        customer_obj = Customer.objects.get(user=user_obj)
    except:
        return JsonResponse({"error":"Not a Customer"})
    
    try:
        so_obj = SaleOrder.objects.get(customer=customer_obj,status='q')
    except:
        return JsonResponse({"error":"Customer does not have Active So"})
    

    print(so_obj.so_lines.all(),'####################')
    
    

    for so_line in so_obj.so_lines.all():
       for product_n_qty in product_n_qty_dict:
           for key,value in product_n_qty.items():
                if int(key) == so_line.product.id:
                  
                  
                  
                  
                  so_line.add_to_cart_update_qty_and_subtotal_so_price(qty=int(value))
                #   so_line.quantity = int(value)
                #   so_line.sub_total = so_line.get_subtotal()
                #   so_line.save()





    
    data ={"success":1,"message":"Cart Updated"}
    return JsonResponse(data)
    

def RemovefromCart(request,product):

    product_obj = Product.objects.get(id=product)
    
    user_obj = request.user
    try:
        customer_obj = Customer.objects.get(user=user_obj)
    except:
        return JsonResponse({"error":"Not a Customer"})
    
    try:
        so_obj = SaleOrder.objects.get(customer=customer_obj,status='q')
    except:
        return JsonResponse({"error":"Customer does not have Active So"})

    

    so_line_obj = so_obj.so_lines.filter(product=product_obj)
    so_line_obj[0].remove_from_cart()

    


    
    


    return redirect("frontend:view-cart")


def blank_value_check_into_form(data):
    for checklist in data:
        if checklist == '':
            return False
    
    return True



class CheckoutView(LoginRequiredMixin,View):
    login_url = '/login/'
    def get(self, request, *args, **kwargs):
        print(request.user.customer,"########")
        customer_obj = request.user.customer
        so_obj = SaleOrder.objects.filter(customer=customer_obj,status='q')
        if so_obj.exists():

            context = {
                'form': CheckoutForm(),
                
            }

            shipping_addr_obj = request.user.customer.get_default_shipping_address()
            if shipping_addr_obj:
                default_shipping_address = shipping_addr_obj.street_address +", " + shipping_addr_obj.country.name
                context.update({"default_shipping_address":default_shipping_address})
            

        
            billing_addr_obj = request.user.customer.get_default_billing_address()
            if billing_addr_obj:
                default_billing_address = billing_addr_obj.street_address +", " + billing_addr_obj.country.name  
                context.update({"default_billing_address":default_billing_address})
            
        

            return render(self.request,"user-frontend/user-ui/checkout.html",context)
        else:
            messages.info(self.request,"You do not have active order to checkout")
            return redirect("frontend:p-list")

    
   
    def post(self, request, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        customer_obj = request.user.customer
        try:
            so_obj = SaleOrder.objects.filter(customer=request.user.customer, status='q')
            so_obj = so_obj [0]
        except:
            return JsonResponse({"error":"You don't have the active order"})

        if form.is_valid():

            shipping_address = form.cleaned_data.get('shipping_address')
            shipping_address2 = form.cleaned_data.get('shipping_address2')
            shipping_country = form.cleaned_data.get('shipping_country')
            shipping_zip = form.cleaned_data.get('shipping_zip')
            same_billing_address = form.cleaned_data.get('same_billing_address')
            set_default_shipping = form.cleaned_data.get('set_default_shipping')
            use_default_shipping = form.cleaned_data.get('use_default_shipping')


            billing_address  = form.cleaned_data.get('billing_address')
            billing_address2 = form.cleaned_data.get('billing_address2')
            billing_country = form.cleaned_data.get('billing_country')
            billing_zip  = form.cleaned_data.get('billing_zip')
            use_default_billing = form.cleaned_data.get('use_default_billing')

frontend/templates/user-frontend/include/navbar.html
{% load static %}
{% load cart_template_tags %}
<!-- <header>
    <div class="logo">
        <img src="{% static 'user-frontend/images/arrow.jpeg' %}" alt="Arrow Img" width="150px">
    </div>
    <nav>
        <ul class="list">
            <li><a href="#">Home</a></li>
            <li><a href="#">Service</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#" class="signup-btn">Sign Up</a></li>
            <li><a href="#"><i class="fas fa-user">Shamu</i></a></li>

            
        </ul>
    </nav>
</header> -->

<!-- ................................ -->

{% if messages %}
{% for message in messages %}

<div class="alert alert-{{ message.tags }} alert-dismissible">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
</div>

<div id="AtttoCardError" class="alert alert-info alert-dismissible" style="display: none;">
  <a href="#"  class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <p>HAHA</p>
</div>

<div class="navbar navbar-default navbar-static-top ">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><img alt="Logo" src="{% static 'user-frontend/images/arrow.jpeg' %}" height="70px"></a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'frontend:frontend' %}">Home</a></li>
          <li class="dropdown menu-large">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Products <b class="caret"></b> </a>
            <ul class="dropdown-menu megamenu">
              <li class="row">
                <div class="col-sm-6 col-md-3">
                  <a href="#" class="thumbnail">
                    <img src="http://placehold.it/150x120" />
                  </a>
                </div>
                <div class="col-sm-6 col-md-3">
                  <a href="#" class="thumbnail">
                    <img src="http://placehold.it/150x120" />
                  </a>
                </div>
                <div class="col-sm-6 col-md-3">
                  <a href="#" class="thumbnail">
                    <img src="http://placehold.it/150x120" />
                  </a>
                </div>
                <div class="col-sm-6 col-md-3">
                  <a href="#" class="thumbnail">
                    <img src="http://placehold.it/150x120" />
                  </a>
                </div>
                <div class="col-sm-6 col-md-3">
                  <a href="#" class="thumbnail">
                    <img src="http://placehold.it/150x120" />
                  </a>
                </div>
                <div class="col-sm-6 col-md-3">
                  <a href="#" class="thumbnail">
                    <img src="http://placehold.it/150x120" />
                  </a>
                </div>
                <div class="col-sm-6 col-md-3">
                  <a href="#" class="thumbnail">
                    <img src="http://placehold.it/150x120" />
                  </a>
                </div>
                <div class="col-sm-6 col-md-3">
                  <a href="#" class="thumbnail">
                    <img src="http://placehold.it/150x120" />
                  </a>
                </div>
              </li>
            </ul>
          </li>
          <li class="dropdown menu-large " style="list-style: none;">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Product Categories <b class="caret"></b></a>
            <ul class="dropdown-menu megamenu row">
                <!-- from context  processor getting categories -->
                {% for cat in categories %}
                    
            
                    
            <li class="col-sm-3">
                <ul>
                    
                
            
                    <li class="dropdown-header"><a class="sub"  href="{% url 'frontend:category-related-product' cat.id %}">{{cat.name}}</a></li>
                    
                    {% for sub in cat.get_children_category  %}
                        <li class="dropdown-header"><a class="sub" href="{% url 'frontend:category-related-product' sub.id %}">{{sub.name}}</a>
                        
                            <ul style="list-style: none;">
                                
                                {% for second in sub.get_children_category  %}
                                    
                            
                                <!-- third categories   -->
                                <li class="dropdown-header"><a class="sub" href="{% url 'frontend:category-related-product' second.id %}">{{second.name}}</a>
                                        <ul>
                                            
                                            {% for third  in second.get_children_category  %}
                                                
                                        
                                                
                                        <li class="dropdown-header"><a class="sub" href="{% url 'frontend:category-related-product' third.id %}">--{{third.name}}</a>
                                            {% endfor %}
                                        
                                        </ul>
                                
                                
                                </li>
                                {% endfor %}
                            </ul>
                        
                        </li>
    
                        <li class="divider"></li>
                        
                    
                            
                    {% endfor %}
                        
                    
                    
                    
                    
                    </a>
                
                        
                
                
                </ul>
            </li>
            {% endfor %}
        
            </ul>
          </li>
          <li class="dropdown menu-large">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Services <b class="caret"></b></a>
            <ul class="dropdown-menu megamenu row">
              <li class="col-sm-3">
                <ul>
                  <li class="dropdown-header">Web Design</li>
                  <li><a href="#">HTML5</a></li>
                  <li class="disabled"><a href="#">CSS</a></li>
                  <li><a href="#">JavaScript</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Web Development</li>
                  <li><a href="#">Websites</a></li>
                  <li><a href="#">Mobile Apps</a></li>
                  <li><a href="#">Responsive</a></li>
                  <li><a href="#">Web Apps</a></li>
                </ul>
              </li>
              <li class="col-sm-3">
                <ul>
                  <li class="dropdown-header">Graphic Design</li>
                  <li><a href="#">PSD</a></li>
                  <li><a href="#">Images</a></li>
                  <li><a href="#">Logos</a></li>
                  <li><a href="#"></a></li>
                  <li><a href="#">Vertical variation</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Database Design</li>
                  <li><a href="#">Single button dropdowns</a></li>
                </ul>
              </li>
              <li class="col-sm-3">
                <ul>
                  <li class="dropdown-header">UI/UX Design</li>
                  <li><a href="#">User Interface</a></li>
                  <li><a href="#">User Experience</a></li>
                  <li><a href="#">Web Designers</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Digital Marketing</li>
                  <li><a href="#">Paid</a></li>
                  <li><a href="#">Social</a></li>
                  <li><a href="#">Content Marketing</a></li>
                </ul>
              </li>
              <li class="col-sm-3">
                <ul>
                  <li class="dropdown-header">Project Management</li>
                  <li><a href="#">Initiating</a></li>
                  <li><a href="#">Planning</a></li>
                  <li><a href="#">Executing</a></li>
                  <li><a href="#">Monitoring</a></li>
                  <li><a href="#">Controlling</a></li>
                  <li><a href="#">Closing</a></li>
                  <li><a href="#">PM Systems</a></li>
                  <li><a href="#">Best Practices</a></li>
                  <li><a href="#">Project Manager</a></li>
                </ul>
              </li>
            </ul>
          </li>

          <!-- service -->
          <li><a href="#">About</a></li>
          <li><a href="/register" class="signup-btn">Sign Up</a></li>
          <!-- <li><a href="#" class="signup-btn"> Cart<i class="fa fa-shopping-cart" aria-hidden="true"><sup class="badge badge-danger">{{request.user|cart_item_count}}</sup></i></a></li> -->

          <li><a href="{% url 'frontend:view-cart' %}"  class="signup-btn onCardShow"> Cart<i class="fa fa-shopping-cart" aria-hidden="true"><sup id="navbarCount" class="badge badge-danger">{{request.user | cart_item_count}}</sup></i></a></li>

          <div class="so-lists">
              <ul>
              
                <!-- to refresh getting the current page -->
                    <!-- {{ request.path }}
                    {{ request.get_full_path }} -->
                <a href="  {{ request.path }}"><i class="fas fa-sync"><sup>Refresh to see qty updated in cart</sup></i></a>
                {% if cart_count %}
                  
                  {% for so_line in cart_count  %}
                  <li>
                    <!-- making flex for li -->
                    <div>
                    <img src="{{so_line.product.image.url}}" width="100px">

                    </div> 
                    <div>
                      <p> Name: {{so_line.product.name}}</p>

                      <p> Price: {{so_line.product.sale_price}}</p>
                      <p> Into :{{so_line.quantity}} +++ KS {{so_line.product.sale_price}}</p>
                      <p>Total Price: {{so_line.sub_total}}</p>
                    </div>
                    
                   



                  </li>
                  <hr />
                  {% endfor %}
                    
                  
                {% endif %}
                  
              
              </ul>
          </div>

          
          {% if request.user %}
          <li class="user-icon-right"><a href="/logout" ><i class="fas fa-user">{{request.user.username}}</i></a></li>
          {% else %}
          <li class="user-icon-right"><a href="/login" ><i class="fas fa-user">{{request.user.username}}</i></a></li>
          {% endif %}
            

        </ul>
      </div>
    </div>
  </div>
  <div class="search">
    <div>
      <form method="post">
        {% csrf_token %}
      <input type="text" name="search" class="search-input" placeholder="Search Product ..."/>
      <input type="submit" value="search" class="search-btn" />
    </form>
  </div> 
  </div>
  <div id="SearchData">

  </div>



  {% include 'user-frontend/include/script.html' %}

    <script type="text/javascript">
     

        $(document).ready(function() {
            $(".onCardShow").on("mouseenter", function() {
              $(".so-lists").show();
            });
            $(".so-lists").on("mouseleave", function() {
              $(this).hide();  //or $('.overlay').hide()
            });

            // onclick search btn
            $(".search-btn").click(function(e){
                $("#SearchData").show()
              
                var url = "{% url 'frontend:search-view' %}" 
                e.preventDefault()
                var searchVal = $(".search-input").val()
                console.log(searchVal)
                if(searchVal === ''){
                  alert("Type something to search")
                }
                else {
                  var csrfmiddlewaretoken = $("input[name=csrfmiddlewaretoken]").val()
                  mydata = {csrfmiddlewaretoken:csrfmiddlewaretoken,search:searchVal}


                  $.ajax({
                    method:'POST',
                    data:mydata,
                    url:url,
                    success:function(res){
                        $("#SearchData").html(res)
                        $("#hidesearchList").click(function(){
                          $("#SearchData").hide()
                          $(".search-input").val('')
                         
                       


                        })
                    },
                    error:function(error){
                      console.log(error)
                    }
                    

                  })
                }

              


               
            })

        },);
          </script>
  {% block javascripts %}{% endblock javascripts %}

frontend/templates/user-frontend/include/script.html
{% load static %}

<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="{% static 'user-frontend/js/main.js' %}"></script>
<script src="{% static 'user-frontend/js/script.js' %}"></script>
<script src="https://unpkg.com/htmx.org@1.6.1"></script>