ERP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.schemas.coreapi import AutoSchema

from rest_framework.routers import DefaultRouter

from rest_framework import routers

router = DefaultRouter()
from rest_framework.schemas.coreapi import AutoSchema

urlpatterns = [
    path('admin/', admin.site.urls),
 
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls")) ,            # UI Kits Html files

    #Customer URL COnfig
    # path("customer/",include('customer.urls')),
    path('customer/',include('customer.urls',namespace="customer")),
    path('product/',include('product.urls',namespace="product")),
    path('sale/',include('sale.urls',namespace="sale")),
    path('inventory/',include('inventory.urls',namespace="inventory")),
    path('purchase/',include('purchase.urls',namespace="purchase")),
    path('invoice/',include('invoice.urls',namespace="invoice")),
    path('ie/',include('imp_exp.urls',namespace="imp-exp")),

    #ALL-API
    path('api/',include('api.urls',namespace="api")),

    #REST FRAMEWORK
    #Add later
    # path(r'api/', include('rest_framework.urls', namespace='rest_framework')),
    # path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
    # path(r'', include(router.urls)),

    #OPENAPIdocs
    path('docs/',include_docs_urls(title="ERP API")),
    path('schema/', get_schema_view(
        title="ERP API LIST",
        description="API for all things …",
        version="1.0.0"
     ), name='openapi-schema'),




    #frontend
    path('frontend/',include('frontend.urls',namespace="frontend")),





     

   
  




    




    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path,include
from .views import (
    ProductCategoryView,
    CategoryList,
    CategoryDetail,
    CategoryDelete,

    #product-uom
    ProductUOMView,
    UOMList,
    UOMDetail,
    UOMDelete,

    ProductView,
    ProductList,
    ProductDetail,
    ProductDelete,
    

    ProductStockDetail,
)
app_name="product"

urlpatterns = [
    path("category/",ProductCategoryView,name="product-category"),
    path("category/list/",CategoryList,name="product-category-list"),
    # path('<int:id>/',ProductCategoryView,"category-update"),
    path('category/<int:id>/', ProductCategoryView,name='category-update'),
    path('category/detail/<int:id>/',CategoryDetail,name="category-detail"),
    path('category/delete/<int:id>/',CategoryDelete,name="category-delete"),





    path("uom/",ProductUOMView,name="product-uom"),
    path("uom/list",UOMList,name="uom-list"),
    path('uom/<int:id>/', ProductUOMView,name='uom-update'),
    path('uom/detail/<int:id>/',UOMDetail,name="uom-detail"),
    path('uom/delete/<int:id>/',UOMDelete,name="uom-delete"),





    


    path("",ProductView,name="product"),
    path("list/",ProductList,name="product-list"),
    path('<int:id>/', ProductView,name='product-update'),
    path('detail/<int:id>/',ProductDetail,name="product-detail"),
    path('delete/<int:id>/',ProductDelete,name="product-delete"),


    path('<int:id>/stock/detail',ProductStockDetail,name="stock-detail")




    

    
    # path("", CustomerView, name="cus"),
    # path('<int:id>/', CustomerView,name='customer-update'),
    # path('list/',Customerlist,name="customer-lists"),
    # path('detail/<int:id>/',CustomerDetail,name="customer-detail"),
    # path('delete/<int:id>/',CustomerDelete,name="customer-delete"),

    
]

templates/custom/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.widgets import CheckboxInput
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from customer.models import Customer


class CustomerForm(forms.ModelForm):
    """Form definition for Book."""
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Enter password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirm password"}))


    class Meta:
        """Meta definition for Bookform."""

        model = Customer
       
        fields = ['name','email','address','country','image','is_customer','is_vendor']
        widgets = {'country': CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-200',
        })}
        widgets = {'is_customer':CheckboxInput()}
        widgets = {'is_vendor':CheckboxInput()}

        
    def __init__(self, *args, **kwargs):
        
        super(CustomerForm,self).__init__(*args, **kwargs)
        if  not self.instance.id is None:
            self.fields.pop('password1')
            self.fields.pop('password2')
            self.fields.pop('is_customer')
            self.fields.pop('is_vendor')
        # self.fields['author'].empty_label = "Select Author"
        self.fields['name'].widget.attrs['placeholder'] = self.fields['name'].label 
        self.fields['email'].widget.attrs['placeholder'] = self.fields['email'].label
        self.fields['address'].widget.attrs['placeholder'] = "Enter your full address"
        self.fields['image'].widget.attrs['placeholder'] = "Image"
       

        for i in self.fields:
            self.fields[i].widget.attrs.update({'class':'form-control'})
    
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        if not password1 == password2:
            msg = "The two password should be match"
            self.add_error('password1',msg)
            self.add_error('password2',msg)








        

       
        

templates/custom/default_index_template.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Page Blank {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

{% endblock stylesheets %}

{% block content %}
    <h1>Product Category Page</h1>
    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-2">Sign up For Customer</h3>
    
                    <span class="mb-0 text-muted">
                        <!-- {% if msg %}
                            {{ msg | safe }}
                        {% else %}
                            Add your credentials
                        {% endif %}  -->
                        
                       
                            
                    </span>
    
                    <br />
                    <br />
    
                    <form role="form" method="post" action="" enctype="multipart/form-data">
    
                        {% csrf_token %}                    
    
                        <div class="input-group mb-3">
                            
                            {{form.name}}
                        </div>
                        <span class="text-danger">{{ form.name.errors }}</span>
    
                       
    
                        
                        
                       
                        <button type="submit" name="register" class="btn btn-primary shadow-2 mb-4">Register</button>
    
                    </form>
    
                   
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/custom/list_table.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Page Blank {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

{% endblock stylesheets %}

{% block content %}


<div class="col-xl-12">
    <div class="card">
        <div class="card-header">
            <a href="{% url 'product:product-category' %}" class="float-right btn btn-primary">Create</a>
            <h5>Product Category Lists</h5>
            <span class="d-block m-t-5">Make some <code>operations</code></span>
           
        </div>
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th class="float-right">Operations</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        
                        {% for cat  in category_lists  %}
                        <tr>
                          
                            <td>{{forloop.counter}}</td>
                            <td>{{cat.name}}</td>
                            <td class="float-right" >
                                <a class="btn btn-primary btn-sm" href="{% url 'product:category-detail' cat.id %}">View</a>

                                <a class="btn btn-success btn-sm" href="{% url 'product:category-update' cat.id %}">Edit</a>
                                <a class="btn btn-danger btn-sm" href="{% url 'product:category-delete' cat.id %}">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                            
                        
                       
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}


<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}