ERP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.schemas.coreapi import AutoSchema

from rest_framework.routers import DefaultRouter

from rest_framework import routers

router = DefaultRouter()
from rest_framework.schemas.coreapi import AutoSchema

urlpatterns = [
    path('admin/', admin.site.urls),
 
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls")) ,            # UI Kits Html files

    #Customer URL COnfig
    # path("customer/",include('customer.urls')),
    path('customer/',include('customer.urls',namespace="customer")),
    path('product/',include('product.urls',namespace="product")),
    path('sale/',include('sale.urls',namespace="sale")),
    path('inventory/',include('inventory.urls',namespace="inventory")),
    path('purchase/',include('purchase.urls',namespace="purchase")),
    path('invoice/',include('invoice.urls',namespace="invoice")),
    path('ie/',include('imp_exp.urls',namespace="imp-exp")),

    #ALL-API
    path('api/',include('api.urls',namespace="api")),

    #REST FRAMEWORK
    #Add later
    # path(r'api/', include('rest_framework.urls', namespace='rest_framework')),
    # path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
    # path(r'', include(router.urls)),

    #OPENAPIdocs
    path('docs/',include_docs_urls(title="ERP API")),
    path('schema/', get_schema_view(
        title="ERP API LIST",
        description="API for all things …",
        version="1.0.0"
     ), name='openapi-schema'),




    #frontend
    path('frontend/',include('frontend.urls',namespace="frontend")),





     

   
  




    




    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

api/product/urls.py
from django.urls import  path,include

from rest_framework.authtoken import views
#router for viewset
from rest_framework.routers import DefaultRouter

from api.product.views import ProductViewSet 

router = DefaultRouter()

app_name = "api"


urlpatterns = [
    # path('',custom_view,name="customer-api"),
   

    
]
router.register(r'', ProductViewSet, basename='product')






urlpatterns += router.urls

product/urls.py
from django.urls import path,include
from .views import (
    ProductCategoryView,
    CategoryList,
    CategoryDetail,
    CategoryDelete,

    #product-uom
    ProductUOMView,
    UOMList,
    UOMDetail,
    UOMDelete,

    ProductView,
    ProductList,
    ProductDetail,
    ProductDelete,
    

    ProductStockDetail,
)
app_name="product"

urlpatterns = [
    path("category/",ProductCategoryView,name="product-category"),
    path("category/list/",CategoryList,name="product-category-list"),
    # path('<int:id>/',ProductCategoryView,"category-update"),
    path('category/<int:id>/', ProductCategoryView,name='category-update'),
    path('category/detail/<int:id>/',CategoryDetail,name="category-detail"),
    path('category/delete/<int:id>/',CategoryDelete,name="category-delete"),





    path("uom/",ProductUOMView,name="product-uom"),
    path("uom/list",UOMList,name="uom-list"),
    path('uom/<int:id>/', ProductUOMView,name='uom-update'),
    path('uom/detail/<int:id>/',UOMDetail,name="uom-detail"),
    path('uom/delete/<int:id>/',UOMDelete,name="uom-delete"),





    


    path("",ProductView,name="product"),
    path("list/",ProductList,name="product-list"),
    path('<int:id>/', ProductView,name='product-update'),
    path('detail/<int:id>/',ProductDetail,name="product-detail"),
    path('delete/<int:id>/',ProductDelete,name="product-delete"),


    path('<int:id>/stock/detail',ProductStockDetail,name="stock-detail")




    

    
    # path("", CustomerView, name="cus"),
    # path('<int:id>/', CustomerView,name='customer-update'),
    # path('list/',Customerlist,name="customer-lists"),
    # path('detail/<int:id>/',CustomerDetail,name="customer-detail"),
    # path('delete/<int:id>/',CustomerDelete,name="customer-delete"),

    
]

product/models.py
# from inventory.models import Stock
from operator import mod
from random import choices
from statistics import mode
from django.db import models

from django.shortcuts import reverse
# for barcode generation
import barcode                      # additional imports
from barcode.writer import ImageWriter
from io import BytesIO
from django.core.files import File
from customer.models import Customer

# Create your models here.

TYPE = (
    ('stock', 'Stockable Product'),
    ('consu', 'Consumable'),
    ('service', 'Service')
    
  
)
PRODUCT_COLORS = (
    ('red','RED'),
    ('green','GREEN'),
    ('black','BLACK'),
    ('yellow','YELLOW'),
    ('silver','SILVER'),


)
PRODUCT_RATINGS= (
    ('one',1),
    ('two',2),
    ('three',3),
    ('four',4),
    ('five',5),


)

class ProductUOM(models.Model):
   
    name =models.CharField(max_length=10)
    

    class Meta:
       

        verbose_name = 'ProductUOM'
        verbose_name_plural = 'ProductUOMs'

    def __str__(self):

        return self.name


class ProductCategory(models.Model):
    
    name = models.CharField(max_length=50)
    category_parent = models.ForeignKey('self', blank=True, null=True, related_name='children',on_delete=models.CASCADE)
    class Meta:
        

        verbose_name = 'ProductCategory'
        verbose_name_plural = 'ProductCategories'

    

    def __str__(self):
        return self.name

    def get_children_category(self):
        return self.children.all()


class Product(models.Model):
    
    name = models.CharField(max_length=50)
    type = models.CharField(choices=TYPE,default='stock',max_length=10)
    category = models.ForeignKey(ProductCategory,related_name="products",on_delete=models.CASCADE)
    uom = models.ForeignKey(ProductUOM,related_name="products",on_delete=models.CASCADE)
    image = models.ImageField()
    slug = models.SlugField()
    barcode = models.ImageField(upload_to='barcodes/', blank=True)
    # barcode = models.IntegerField(blank=True,null=True)
    sale_price = models.FloatField(blank=True,null=True)
    purchase_price = models.FloatField(blank=True,null=True)
    vendor = models.ForeignKey(Customer,related_name="products",on_delete=models.CASCADE,blank=True,null=True)
    color = models.CharField(choices=PRODUCT_COLORS,default='red',max_length=10,blank=True,null=True)
    product_ratings= models.CharField(choices=PRODUCT_RATINGS,default='one',max_length=10,blank=True,null=True)
    
    class Meta:
        

        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
       return self.name
    
    def get_absolute_url(self):
        
        return reverse('product:product-detail', kwargs={'id': self.id})

    
    #for just showing on the official store detail vendor page
    def get_10_percent_discount(self):
        percentage = self.sale_price / 10
        new_price =  percentage + self.sale_price   
        return new_price


   

    #getting stock total count product detail page
    def get_total_stock_quantity(self):
        total = 0
        for stock in self.stocks.all():
            total +=  stock.quantity
        return total

    def get_all_location_for_product_and_relative_qty(self):
        # import pdb;pdb.set_trace()
        location_lits = []
        qty_lists = []
        for stock  in self.stocks.all():
            location_obj = stock.location_id
            location_lits.append(location_obj)
            qty_lists.append(stock.quantity)
        
        stock_location_and_its_quantity =list(zip(location_lits, qty_lists))
        
        return stock_location_and_its_quantity

        

    def save(self, *args, **kwargs):          # overriding save() 
        COD128 = barcode.get_barcode_class('code128')
        rv = BytesIO()
        code = COD128(f'{self.name}', writer=ImageWriter()).write(rv)
        self.barcode.save(f'{self.name}.png', File(rv), save=False)
        return super().save(*args, **kwargs)

    #1-2-2022
    def get_colors(self):
        return self.color

product/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.widgets import CheckboxInput
from django_countries.fields import CountryField

from .models import Product,ProductCategory,ProductUOM

#Product Category
class ProductCategroyForm(forms.ModelForm):
    

    class Meta:
        

        model = ProductCategory
        fields = ['name']
    
    def __init__(self,*args, **kwargs):
        super(ProductCategroyForm,self).__init__(*args, **kwargs)

        for i in self.fields:
            self.fields[i].widget.attrs.update({'class':'form-control'})
        self.fields['name'].widget.attrs['placeholder'] = "Enter Category Name"
        


class ProductUOMForm(forms.ModelForm):
    

    class Meta:
        

        model = ProductUOM
        fields = ['name']
    
    def __init__(self,*args, **kwargs):
        super(ProductUOMForm,self).__init__(*args, **kwargs)

        for i in self.fields:
            self.fields[i].widget.attrs.update({'class':'form-control'})
        self.fields['name'].widget.attrs['placeholder'] = "Enter UOM Name"

class ProductForm(forms.ModelForm):
  

    class Meta:
        

        model = Product
        fields = ['name','type','category','uom','image','slug','barcode']
    
    def __init__(self,*args, **kwargs):
        super(ProductForm,self).__init__(*args, **kwargs)

        for i in self.fields:
            self.fields[i].widget.attrs.update({'class':'form-control'})
        self.fields['name'].widget.attrs['placeholder'] = "Enter Name"
        self.fields['slug'].widget.attrs['placeholder'] = "Fill Slugname"

        self.fields['category'].empty_label = "Select Category"
        self.fields['uom'].empty_label = "Select UOM"

api/product/views.py
from rest_framework import parsers
from api.views import *
from .serializers import ProductSerializer
from product.models import *
from rest_framework import parsers

class ProductViewSet(viewsets.ModelViewSet):
    """
    List all books, or create a new book.
    """
    # parser_classes = [parsers.JSONParser,parsers.MultiPartParser]
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    

product/views.py
from inventory.models import Location,Stock

from product.forms import ProductUOMForm,ProductCategroyForm,ProductForm
from django.shortcuts import redirect, render
from django.http import HttpResponse
# from .forms import ProductCategroyForm
from product.models import ProductUOM,Product,ProductCategory
# Create your views here.

#Product Category
def ProductCategoryView(request,id=0):
    if request.method == "GET":
        if id == 0:
            form = ProductCategroyForm()
        else:
            category_obj = ProductCategory.objects.get(pk=id)
            form = ProductCategroyForm(instance=category_obj)    
        return render(request,"product_category/index.html",{"form":form})
    else:
        if id ==0 :
            form = ProductCategroyForm(request.POST)
        else:
            category_obj = ProductCategory.objects.get(pk=id)
            form = ProductCategroyForm(request.POST,instance=category_obj)
        if form.is_valid():
            form.save()
            return redirect("product:product-category-list")
        


def CategoryList(request):
    category_lists =  ProductCategory.objects.all()
    context = {
        "category_lists":category_lists
    }
    return render(request,"product_category/list.html",context)

def CategoryDetail(request,id):
    category_obj = ProductCategory.objects.get(pk=id)

    context = {
        "category":category_obj
    }
    return render(request,"product_category/detail.html",context)

def CategoryDelete(request,id):
    category_obj = ProductCategory.objects.get(pk=id)
    category_obj.delete()
    return redirect("product:product-category-list")


#ProductUOM
def ProductUOMView(request,id=0):

    if request.method == "GET":
        if id == 0:
            form = ProductUOMForm()
        else:
            category_obj = ProductUOM.objects.get(pk=id)
            form = ProductUOMForm(instance=category_obj)    
        return render(request,"product_uom/index.html",{"form":form})
    else:
        if id ==0 :
            form = ProductUOMForm(request.POST)
        else:
            category_obj = ProductUOM.objects.get(pk=id)
            form = ProductUOMForm(request.POST,instance=category_obj)
        if form.is_valid():
            form.save()
            return redirect("product:uom-list")


def UOMList(request):
    uom_lists = ProductUOM.objects.all()
    context = {
        "uom_lists":uom_lists
    }
    return render(request,"product_uom/list.html",context)



    

def UOMDetail(request,id):
    uom_obj = ProductUOM.objects.get(pk=id)

    context = {
        "uom":uom_obj
    }
    return render(request,"product_uom/detail.html",context)

def UOMDelete(request,id):
    uom_obj = ProductUOM.objects.get(pk=id)
    uom_obj.delete()
    return redirect("product:uom-list")




#Product
def ProductView(request,id=0):
    # return render(request,"product/index.html")
    if request.method == "GET":
        if id == 0:
            form = ProductForm()
        else:
            product_obj = Product.objects.get(pk=id)
            form = ProductForm(instance=product_obj)
        return render(request,"product/index.html",{"form":form})
    else:
        if id == 0:
            form = ProductForm(request.POST,request.FILES)
        else:
            product_obj = Product.objects.get(pk=id)
            form = ProductForm(request.POST,request.FILES, instance=product_obj)
        if form.is_valid():
            form.save()
        return redirect("product:product-list")


def ProductList(request):
    product_lists = Product.objects.all()
    context = {
        "product_lists":product_lists
    }

    return render(request,"product/list.html",context)
    

def ProductDetail(request,id):
    try:
        product_obj = Product.objects.get(pk=id)

    except:
        context = {
            "page":"Product Detail",
            "detail":"Product detail can't found"
        }
        return render(request,"page-404.html",context)
   
    context = {
        "product":product_obj,
        
    }

    return render(request,"product/detail.html",context)

def ProductDelete(request,id):
    product_obj = Product.objects.get(pk=id)
    product_obj.delete()
    return redirect("product:product-list")



def ProductStockDetail(request,id):
    product = Product.objects.get(id=id)
    context = {
        "product":product
    }
    
    return render(request,"stock_location_detail/location_detail.html",context)

product/templates/product/detail.html
{% extends "layouts/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Page Blank {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

{% endblock stylesheets %}

{% block content %}
    <h5 class="mb-5">Product Detail View</h5>
       <!-- [ Hover-table ] start -->
       <!-- ...............On hand..................... -->
        <div class="col-md-12">
            <div class="col-md-2"></div>
            <div class="col-md-2 float-right">
                <div class="card">
                    <div class="card-header">
                       
                        
                        <a href="{% url 'product:stock-detail' product.id %}">On Hand {{product.get_total_stock_quantity}} </a>
                        
                    </div>
                </div>
            </div>
    <!-- ...............On hand..................... -->

        </div>
       <p> {{product.name}} </p>
       <p> {{product.get_type_display}} </p>
       <p> {{product.category.name}} </p>
       <p> {{product.uom.name}} </p>
       <p> {{product.slug}} </p>


       <p> {{product.sale_price}} </p>
       <p> {{product.purchase_price}} </p>
       <img src="{{product.barcode.url}}">

       <img src="{{product.image.url}}">
       

       
    <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
        class="nav-item active">
        <a href="{% url 'product:product-update' product.id %}" class="nav-link "><span class="pcoded-micon">
            <i class="feather icon-edit">

            </i></span><span class="pcoded-mtext">Edit</span></a>
    </li>

    <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
        class="nav-item active">
        <a href="{% url 'product:product-delete' product.id %}" class="nav-link "><span class="pcoded-micon">
            <i class="feather icon-delete">

            </i></span><span class="pcoded-mtext">Delete</span></a>
    </li>

        






{% endblock content %}

    <!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

product/templates/product/index.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Page Blank {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

{% endblock stylesheets %}

{% block content %}
    <h1>Product Registration Page</h1>
    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-2">Product Registration</h3>
    
                    <span class="mb-0 text-muted">
                        <!-- {% if msg %}
                            {{ msg | safe }}
                        {% else %}
                            Add your credentials
                        {% endif %}  -->
                        
                       
                            
                    </span>
    
                    <br />
                    <br />
    
                    <form role="form" method="post" action="" enctype="multipart/form-data">
    
                        {% csrf_token %}                    
    
                        <div class="input-group mb-3">
                            
                            {{form.name}}
                        </div>
                        <span class="text-danger">{{ form.name.errors }}</span>

                        <div class="input-group mb-3">
                            
                            {{form.type}}
                        </div>
                        <span class="text-danger">{{ form.type.errors }}</span>

                        <div class="input-group mb-3">
                            
                            {{form.category}}
                        </div>
                        <span class="text-danger">{{ form.category.errors }}</span>

                        <div class="input-group mb-3">
                            
                            {{form.uom}}
                        </div>
                        <span class="text-danger">{{ form.uom.errors }}</span>

                        <label class="float-left">Select Image:</label><br>
                        <div class="input-group mb-3">
                            
                            {{form.image}}
                        </div>
                        <span class="text-danger">{{ form.image.errors }}</span>
                        <label class="float-left">Select Barcode:</label><br>
                        <div class="input-group mb-3">
                            
                            {{form.barcode}}
                        </div>
                        <span class="text-danger">{{ form.barcode.errors }}</span>


                        <div class="input-group mb-3">
                            
                            {{form.slug}}
                        </div>
                        <span class="text-danger">{{ form.slug.errors }}</span>



    
                       
    
                        
                        
                       
                        <button type="submit" name="register" class="btn btn-primary shadow-2 mb-4">Register</button>
    
                    </form>
    
                   
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

product/templates/product/list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Page Blank {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

{% endblock stylesheets %}

{% block content %}

<div class="col-xl-12 col-md-12">
    <div class="card Recent-Users">
        <div class="card-header">
            <a href="{% url 'product:product' %}" class="float-right btn btn-primary">Create</a>
            <h5>Product</h5>
        </div>
        <div class="card-block px-0 py-3">
            <div class="table-responsive">
                <table id="table" class="table table-hover">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Image</th>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Category</th>
                            <th>Uom</th>
                            <th>Barcode</th>
                            <th>Sale P</th>
                            <th>Purchase P</th>
                            <th>Slug</th>
                            <th>Operations</th>
                           
                            
                        </tr>
                    </thead>
                    <tbody>

                        
                        {% for p  in product_lists  %}
                            
                       
                            
                        <tr class="unread">
                            <td>{{forloop.counter}}</td>
                            <td><a href="{{p.get_absolute_url}}">
                                <img class="rounded-circle" style="width:40px;" 
                                src="{{p.image.url}}" alt="activity-user">
                                </a>
                            </td>
                            <td>
                                {{p.name}}
                            </td>
                            <td>{{p.get_type_display}}</td>
                            <td>{{p.category.name}}</td>
                            <td>{{p.uom.name}}</td>
                            <td><img class="rounded-circle" style="width:60px;" src="{{p.barcode.url}}" alt="activity-user"></td>
                            <td>{{p.sale_price}}</td>
                            <td>{{p.purchase_price}} </td>
                           <td> {{p.slug}} </td>
                              
                            <td><a href="{% url 'product:product-update' p.id %}" 
                                class="label theme-bg2 text-white f-12">Edit</a>
                                <a href="{% url 'product:product-delete' p.id %}" 
                                class="label theme-bg text-white f-12">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                       
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<!-- <script type = "text/javascript">
    $(document).ready(function(){
        $('#table').DataTable();
    });
</script> -->
{% endblock javascripts %}