ERP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.schemas.coreapi import AutoSchema

from rest_framework.routers import DefaultRouter

from rest_framework import routers

router = DefaultRouter()
from rest_framework.schemas.coreapi import AutoSchema

urlpatterns = [
    path('admin/', admin.site.urls),
 
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls")) ,            # UI Kits Html files

    #Customer URL COnfig
    # path("customer/",include('customer.urls')),
    path('customer/',include('customer.urls',namespace="customer")),
    path('product/',include('product.urls',namespace="product")),
    path('sale/',include('sale.urls',namespace="sale")),
    path('inventory/',include('inventory.urls',namespace="inventory")),
    path('purchase/',include('purchase.urls',namespace="purchase")),
    path('invoice/',include('invoice.urls',namespace="invoice")),
    path('ie/',include('imp_exp.urls',namespace="imp-exp")),

    #ALL-API
    path('api/',include('api.urls',namespace="api")),

    #REST FRAMEWORK
    #Add later
    # path(r'api/', include('rest_framework.urls', namespace='rest_framework')),
    # path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
    # path(r'', include(router.urls)),

    #OPENAPIdocs
    path('docs/',include_docs_urls(title="ERP API")),
    path('schema/', get_schema_view(
        title="ERP API LIST",
        description="API for all things …",
        version="1.0.0"
     ), name='openapi-schema'),




    #frontend
    path('frontend/',include('frontend.urls',namespace="frontend")),





     

   
  




    




    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path,include
from django.contrib.auth.decorators import login_required

from .views import (
    IndexView,
    GetCategoryRelatedProduct,
    ProductListView,
    ProductDetail,
    AddtoCart,
    BuyProduct,
    ViewAddtoCartItem,
    UpdateCart,
    RemovefromCart,
    CheckoutView,
    SearchView,
    VendorDetailView,
    AddCoupon,
    htmx_test_view,
    rating_test
   
)

app_name="frontend"

urlpatterns = [
    path("", IndexView, name="frontend"),
    path("category/<int:category>/", GetCategoryRelatedProduct, name="category-related-product"),
    path('product-list',ProductListView,name="p-list"),
    path('product/<int:product>/',ProductDetail,name="p-detail"),
    path('add-to-cart/<int:product>/',AddtoCart,name="add-to-cart"),
    path('buy-product/<int:product>/',BuyProduct,name="buy-product"), #create so and qty update
    path('cart/',ViewAddtoCartItem,name="view-cart"),
    path('update-cart/',UpdateCart,name="update-cart"),
    path('removefromcart/<int:product>/',RemovefromCart,name="remove-from-cart"),
    path('checkout/',CheckoutView.as_view(),name="checkout-view"),
    path('search/',SearchView,name="search-view"),
    path('vendor/<int:id>/',VendorDetailView.as_view(),name="vendor-detail"),
    path('add-coupon',AddCoupon,name="add-coupon-view"),
    path('test/',htmx_test_view,name="htmx-test"),
    path('rating/',rating_test,name='rating-test')

    

   














    


   

    
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_zip = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    # payment_option = forms.ChoiceField(
    #     widget=forms.RadioSelect(attrs={
    #         'class':'custom-control-input',
    #     }), choices=PAYMENT_CHOICES)

    def __init__(self,*args, **kwargs):
        super(CheckoutForm,self).__init__(*args, **kwargs)

        for i in self.fields:
            self.fields[i].widget.attrs.update({'class':'form-control'})
        
       
       


class CouponForm(forms.Form):
    
    code = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Promo Code',
        'class':'form-control',
        'aria-label':"Recipient's username",
        'aria-describedby':'basic-addon2'

    }))

frontend/views.py
from curses.ascii import HT
from http.client import HTTPResponse
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http import JsonResponse,HttpResponse
from django.shortcuts import redirect, render
from django.utils import tree
from product.models import Product,ProductCategory
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from customer.models import Addr, Customer
from sale.models import SaleOrder,SaleOrderLine,Coupon
import datetime
#method for creating ref number 
from sale.views import  create_so_num
# Create your views here.
import json 
from django.views.generic import View
from frontend.forms import CheckoutForm
# from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from product.models import PRODUCT_COLORS,PRODUCT_RATINGS


def IndexView(request):
    product_lists = Product.objects.all()
    vendor_lists = Customer.objects.filter(is_vendor=True)
    context = {
        "product_lists": product_lists,
        "vendor_lists":vendor_lists
       
    }
    return render(request,"user-frontend/user-ui/index.html",context)


def ProductListView(request):
    product_lists = Product.objects.all()
    context = {
        "product_lists":product_lists
    }

    return render(request,"user-frontend/user-ui/product-list.html",context)

def GetCategoryRelatedProduct(request,category):
    category_lists = ProductCategory.objects.all()[:5]

    try:
        category_obj =  ProductCategory.objects.get(id = category)
    except ObjectDoesNotExist:
        return HttpResponse("Not related category found")
    
    product_lists = Product.objects.filter(category=category_obj)

    context = {
        "product_lists":product_lists,
        "category_lists":category_lists
    }

    return render(request,"user-frontend/user-ui/category_base_product_list.html",context)


    # product_lists = Product.objects.all()
    # data = {
    #     "name":product_lists[0].name,
    #     "category":product_lists[0].category.name,
    #     "image":product_lists[0].image.url,
    #     "slug":product_lists[0].slug
    #     # "name":product_lists[0].name,


    # }
    # return JsonResponse(data)


def ProductDetail(request,product):

    product_obj = get_object_or_404(Product, pk=product)
    product_lists = Product.objects.exclude(id=product)[:3]
    context = {
        "product":product_obj,
        "product_lists":product_lists,
    }

    return render(request,"user-frontend/user-ui/product_detail.html",context)


# @login_required
def AddtoCart(request,product):


    if not request.user.is_authenticated:
        return JsonResponse({"error":"Login First"})
 
    return JsonResponse({"data":"Add to Cart Called"})


def BuyProduct(request,product):

   

    if not request.user.is_authenticated:
        return JsonResponse({"error":"Login First"})
 
    product_id = request.POST.get('productid')
    qty = request.POST.get('quantity')
    qty = int(qty)

    
    product_id = int(product_id)

    product_obj = Product.objects.get(id=product_id)


    user_obj = request.user
    try:
        customer_obj = Customer.objects.get(user=user_obj)
    except:
        return JsonResponse({"error":"Not a Customer"})
    # so_obj = SaleOrder.objects.get_or_create(customer=customer_obj,order_date=datetime.datetime.today())
    #filter by customer n status, not by date, if SO need to crete order date, so passing just 
    # https://stackoverflow.com/questions/13610896/django-get-or-create-how-to-say-commit-false
    defaults = {'order_date': datetime.datetime.today()}
    so_obj = SaleOrder.objects.get_or_create(customer=customer_obj,status='q',defaults=defaults)

    so_obj = so_obj[0]
    so_obj.ref = create_so_num()
    so_obj.save()
   
    

    so_line_obj = SaleOrderLine.objects.filter(sale_order=so_obj,product=product_obj)
    print(so_line_obj)
    if so_line_obj.exists():
        so_line_obj= so_line_obj[0]
        # so_line_obj.quantity += qty
        # so_line_obj.sub_total = so_line_obj.get_subtotal()

        # so_line_obj.save()

        # #update the sale order total price in Sale order object
        # so_obj = so_line_obj.sale_order
        # so_obj.total_price = so_obj.sale_order_total()
        # so_obj.save()
        qty_updated = so_line_obj.quantity +  qty
        so_line_obj.add_to_cart_update_qty_and_subtotal_so_price(qty=qty_updated)
        return JsonResponse({"data":"Qty Updated"})
    else:
        so_line_obj = SaleOrderLine.objects.create(sale_order=so_obj,product=product_obj,quantity=qty)
        so_line_obj.add_to_cart_update_qty_and_subtotal_so_price(qty=qty)
        
        
        # so_line_obj.sub_total = so_line_obj.get_subtotal()
        # so_line_obj.save()

        # #update the sale order total price in Sale order object
        
        # so_obj = so_line_obj.sale_order
        # so_obj.total_price = so_obj.sale_order_total()
        # so_obj.save()


        

        #updating on the cart Navbar Count,So i return count to the client

         



    return JsonResponse({"data":"created","count":1})


def ViewAddtoCartItem(request):

    return render(request,"user-frontend/user-ui/view_add_to_cart.html")




def UpdateCart(request):
    #products getting from ajax is JSON STRINGFY, so need to change python object
    product_and_qty_json_lists = request.POST['products']
    product_n_qty_dict = json.loads(product_and_qty_json_lists)

    user_obj = request.user
    try:
        customer_obj = Customer.objects.get(user=user_obj)
    except:
        return JsonResponse({"error":"Not a Customer"})
    
    try:
        so_obj = SaleOrder.objects.get(customer=customer_obj,status='q')
    except:
        return JsonResponse({"error":"Customer does not have Active So"})
    

    print(so_obj.so_lines.all(),'####################')
    
    

    for so_line in so_obj.so_lines.all():
       for product_n_qty in product_n_qty_dict:
           for key,value in product_n_qty.items():
                if int(key) == so_line.product.id:
                  
                  
                  
                  
                  so_line.add_to_cart_update_qty_and_subtotal_so_price(qty=int(value))
                #   so_line.quantity = int(value)
                #   so_line.sub_total = so_line.get_subtotal()
                #   so_line.save()





    
    data ={"success":1,"message":"Cart Updated"}
    return JsonResponse(data)
    

def RemovefromCart(request,product):

    product_obj = Product.objects.get(id=product)
    
    user_obj = request.user
    try:
        customer_obj = Customer.objects.get(user=user_obj)
    except:
        return JsonResponse({"error":"Not a Customer"})
    
    try:
        so_obj = SaleOrder.objects.get(customer=customer_obj,status='q')
    except:
        return JsonResponse({"error":"Customer does not have Active So"})

    

    so_line_obj = so_obj.so_lines.filter(product=product_obj)
    so_line_obj[0].remove_from_cart()

    


    
    


    return redirect("frontend:view-cart")


def blank_value_check_into_form(data):
    for checklist in data:
        if checklist == '':
            return False
    
    return True



class CheckoutView(LoginRequiredMixin,View):
    login_url = '/login/'
    def get(self, request, *args, **kwargs):
        print(request.user.customer,"########")
        customer_obj = request.user.customer
        so_obj = SaleOrder.objects.filter(customer=customer_obj,status='q')
        if so_obj.exists():

            context = {
                'form': CheckoutForm(),
                
            }

            shipping_addr_obj = request.user.customer.get_default_shipping_address()
            if shipping_addr_obj:
                default_shipping_address = shipping_addr_obj.street_address +", " + shipping_addr_obj.country.name
                context.update({"default_shipping_address":default_shipping_address})
            

        
            billing_addr_obj = request.user.customer.get_default_billing_address()
            if billing_addr_obj:
                default_billing_address = billing_addr_obj.street_address +", " + billing_addr_obj.country.name  
                context.update({"default_billing_address":default_billing_address})
            
        

            return render(self.request,"user-frontend/user-ui/checkout.html",context)
        else:
            messages.info(self.request,"You do not have active order to checkout")
            return redirect("frontend:p-list")

    
   
    def post(self, request, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        customer_obj = request.user.customer
        try:
            so_obj = SaleOrder.objects.filter(customer=request.user.customer, status='q')
            so_obj = so_obj [0]
        except:
            return JsonResponse({"error":"You don't have the active order"})

        if form.is_valid():

            shipping_address = form.cleaned_data.get('shipping_address')
            shipping_address2 = form.cleaned_data.get('shipping_address2')
            shipping_country = form.cleaned_data.get('shipping_country')
            shipping_zip = form.cleaned_data.get('shipping_zip')
            same_billing_address = form.cleaned_data.get('same_billing_address')
            set_default_shipping = form.cleaned_data.get('set_default_shipping')
            use_default_shipping = form.cleaned_data.get('use_default_shipping')


            billing_address  = form.cleaned_data.get('billing_address')
            billing_address2 = form.cleaned_data.get('billing_address2')
            billing_country = form.cleaned_data.get('billing_country')
            billing_zip  = form.cleaned_data.get('billing_zip')
            use_default_billing = form.cleaned_data.get('use_default_billing')

frontend/templates/user-frontend/user-ui/category_base_product_list.html
{% extends 'user-frontend/base.html' %}
{% load static %}



{% block content %}
<div class="category-base">

    
    <div class="hola">

        {% for product in product_lists %}
        <div class="hola-item">
            <p class="text-center"><span class="badge badge-success">{{product.category.name}}</span></p>
        <a href="#"><img src="{{product.image.url}}" width="200px" height="100px"></a>
        <p>{{product.name}}</p>
        <p>Category:{{product.category.name}}</p>
        <p>Price: {{product.sale_price}}</p>
        <p class="card-text">Some quick example text tod's content.</p>
        <a href="{% url 'frontend:p-detail' product.id %}" class="view-btn" style="display: block;">View</a>
        </div>
    
    
        {% endfor %}
    </div>

    <div class="category-right">
        
            <p class="badge badge-success">Feature Product Categories</p>
            
            {% for cat  in category_lists %}
            <ul>
                <li><a href="{% url 'frontend:category-related-product' cat.id %}">{{cat.name}}</a></li>
            </ul>
            {% endfor %}
                
            
         
    </div>
</div>

   




{% endblock content %}
    



{% block javascripts %}
    
{% endblock javascripts %}
    

frontend/templates/user-frontend/user-ui/filter_search_on_vendor.html
{% load static %}
<div>
    <!-- <img class="loadimg" src="{% static 'user-frontend/images/img.png' %}" height="300px"> -->
    <button id="hidesearchList" class="btn btn-sm btn-danger" ><i class="fa fa-times" aria-hidden="true"></i></button>
<h5 class="text-center  text-primary" >Filter Result Lists</h5>
    <div class="os-product-lists-card">
        <div class="os-card">
            {% if product_lists.count > 0 %}
                {% for product in product_lists %}
            <div class="os-card-item">
                <p class="text-center"><span class="badge badge-success">{{product.category.name}}</span></p>
            <a href="{% url 'frontend:p-detail' product.id %}"><img src="{{product.image.url}}" width="200px" height="100px"></a>
            <p class="badge badge-primary">Official Store</p>
            <p>{{product.name}}</p>
        
            <p>Price: {{product.sale_price}}</p>
            <p><small><del>Ks {{product.get_10_percent_discount}}</del> -10%  <span class="free">FREE</span></small></p>
            {% include "user-frontend/user-ui/partial/product_rating_template.html" %}
            
            <p><small>Myanmar[Burma]</small></p>
            
            
            </div>
        
        
        
            {% endfor %}
            {% else %}
           
            <h3 class="text text-center">No Products Found 
                <i style="color:silver; font-size: 20px;" class="fa fa-frown-open" aria-hidden="true"></i>
                <i style="color:silver; font-size: 30px;" class="fa fa-heart-broken" aria-hidden="true"></i>
                <i style="color:silver; font-size: 40px;" class="fa fa-sad-cry" aria-hidden="true"></i>
                
            </h3>
            {% endif %}
        </div>
    </div>
</div>
<hr>
{% block javascripts %}
<!-- for htmx color filter, to return to normal state, url -->
<script>
    

                  $("#hidesearchList").click(function(){
                       
                        var originLocation= window.location.href
                        var pageUrl = originLocation
                        var gg =pageUrl.indexOf('?')
                        var updatedLocation = pageUrl.split('?')
                        console.log(updatedLocation[0])
                        window.location.href=updatedLocation[0]
                        
                        
                          

                        })
</script>
  
{% endblock javascripts %}

frontend/templates/user-frontend/user-ui/index.html
{% extends 'user-frontend/base.html' %}
{% load static %}

{% block content %}


<main>
    <div class="content-left">
        <h1>online</h1>
        <h2>shopping</h2>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam distinctio temporibus nemo odit consequatur cum provident 
            laboriosam tempora. Tenetur aspernatur repellendus dicta nostrum.</p>
           <a class="cta" href="{% url 'frontend:p-list' %}" >Start shopping</a>
    </div>
    

    <div class="content-right">
        <img class="hero-img" src="{% static 'user-frontend/images/img.png' %}" alt="Arrow Img">
    </div>
   
</main>




<h1 class="myh1">User Frontend</h1>


<a href="#" id="ggwp">CLICK TO GET</a>
<h3 class="promotion-banner">Official Stores</h3>




<!-- .......Carousel With Official Store......... -->

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
  
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
      
    <div class="item active">
      <div class="official-store-card1">
          {% for vendor  in vendor_lists %}
          <div class="official-store-card-item">
          
                  <a href="{% url 'frontend:vendor-detail' vendor.id %}"><img src="{{vendor.image.url}}"  class="img-center" width="150px" height="80px"></a>
                  <p>{{vendor.name}}</p>
                 
                  
              
              
              
      
          </div>
         {% endfor %} 
        
         
      </div>
    </div>
    <div class="item">
      <div class="official-store-card1">
        {% for vendor  in vendor_lists %}
        <div class="official-store-card-item">
        
                <a href="{% url 'frontend:vendor-detail' vendor.id %}"><img src="{{vendor.image.url}}"  class="img-center" width="150px" height="80px"></a>
                <p>{{vendor.name}}</p>
               
                
            
            
            
    
        </div>
       {% endfor %} 
      
       
    </div>

    </div>
  
    
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left text-primary" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right text-primary" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!-- .......................... -->


    
<div class="official-store-card1">
    {% for vendor  in vendor_lists %}
    <div class="official-store-card-item">
    
            <a href="{% url 'frontend:vendor-detail' vendor.id %}"><img src="{{vendor.image.url}}"  class="img-center" width="150px" height="80px"></a>
            <p>{{vendor.name}}</p>
           
            
        
        
        

    </div>
   {% endfor %} 
  
   
</div>
<hr>








<div class="card1">

    {% for product in product_lists %}
    <div class="card-item">
        <p class="text-center"><span class="badge badge-success"></span></p>
    <a href="#"><img src="{{product.image.url}}" width="200px" height="100px"></a>
    <p>{{product.name}}</p>
    <p>Category:{{product.category.name}}</p>
    <p>Price: {{product.sale_price}}</p>
    <p class="card-text">Some quick example text tod's content.</p>
    <a href="{% url 'frontend:p-detail' product.id %}" class="view-btn" style="display: block;">View</a>
    </div>
   
  
    {% endfor %}
</div>


{% endblock content %}


{% block javascripts %}
    <!-- <script>
        console.log("Index Called")
        var listName = [];
            $(".sub").click(function(){
            //    $(".sub").each(function(){
            //        listName.push($(this).attr('href'))
                   
            //    })
              var myhref=  $(this).attr('href')
              var data =  myhref.split("/");
              var idNumber = data[2]
                var link = '/rango/like_category/{idNumber}'
                alert("YOYO")
            alert(link)
             
              alert(typeof(data))
            //   alert(data[length(data) ])
                var NewURL =  'http://localhost:8000/frontend/' + idNumber 
                alert(NewURL)
               var urls = "{% url 'frontend:category-related-product' 24  %}" 
               alert(urls) 

            //  alert(myhref)

             $.ajax({
                 type:'GET',
                 url:NewURL,

                 success:function(response){
                     console.log(response)
                     alert(response)
                     alert(urls)
                 },

                 error:function(response){
                     console.log(response)
                 }
                  
             })
            })

        $("#ggwp").click(function(e){
            
            

            $.ajax({
            type:'GET',
            url: "http://localhost:8000/frontend/21/",
            
            success:function(response){
                console.log(response)
            },

            error:function(respose){
                console.log(respose)
            }



        })

       

        
        
        })
    </script> -->


{% endblock javascripts %}

frontend/templates/user-frontend/user-ui/product_detail.html
{% extends 'user-frontend/base.html' %}
{% load static %}



{% block content %}
<p>Product Detail</p>




<div  class="product-detail">
    <div class="detail-content">
        <div class="img-part">
            <h1>Img Part</h1>
            <img src="{% static 'user-frontend/images/img.png' %}" height="300px">
        </div>

        <div class="small-description">
            <h1>{{product.name}}</h1> <span class="badge badge-success">{{product.category.name}}</span>
            <p><del>{{product.sale_price}}</del> KS</p>
            <p>{{product.sale_price}} KS</p>
            <form>
              {% csrf_token %}
            <!-- <button class="minus-btn">-</button> -->
            <input type="button" id="minus" data-id="{{product.id}}" value="-" class="plus-btn" />

            <input id="quantity" type="number"  min="0" value="1">
            <!-- <button id="plus" class="plus-btn" data-id="{{product.id}}">+</button> -->
            <input type="button" id="plus" data-id="{{product.id}}" value="+" class="plus-btn" />
            <!-- <input type="button" id="btnsave" value="save" class="btn btn-success btn-sm " /> -->
            <input type="button" id="buyproduct" data-id="{{product.id}}" value="Buy" class="plus-btn" />

          </form>


          

            <a href="#" class="add-to-wish-list">  <i class="fa fa-heart" aria-hidden="true"></i>Add to wish list</a>
            <p></p>

        </div>
    </div>
    <div class="detail-feature-product">
       <p class="feature-product">Feature Products</p>
       <ul>
           
           {% for product in product_lists  %}
               
           
               
           <li>
             <a href="{% url 'frontend:p-detail' product.id %}"><img src="{{product.image.url}}" width="80px" height="60px"> </a>
                <span>{{product.name}}</span> -
               <span class="text-center"> {{product.sale_price}} Ks</span>
           
            </li>
            <hr>
           {% endfor %}
       </ul>
    </div>
</div>

{% endblock content %}
    



{% block javascripts %}

  <script type="text/javascript">
    console.log("Add to cart")
    $(document).ready(function(){
      if($("input[type='number']").val() == "1"){
        $("input[type='number']").prop('disabled', true);
    }
    })
    

    $("#minus").click(function(){
      
    if($("input[type='number']").val() == "1"){
        $("input[type='number']").prop('disabled', true);
    }else{
      
       var qty = $("#quantity").val()
       var qty =  parseInt(qty)
       $("#quantity").val(qty-1)
    }
    })



    $("#plus").click(function(){
      var dataId = $(this).attr('data-id')
      var intdataId = parseInt(dataId)

      
      var qty = $("#quantity").val()
      var qty =  parseInt(qty)
      $("#quantity").val(qty+1)
     
     
      var url = "{% url 'frontend:add-to-cart' 24  %}" 
      var csrfmiddlewaretoken = $("input[name=csrfmiddlewaretoken]").val()
      mydata = {csrfmiddlewaretoken:csrfmiddlewaretoken, productid:intdataId}
      $.ajax({
        method:'POST',
        url:url,
        data:mydata,

        success:function(response){
          console.log(response,'########')
          
          
        },
        error:function(error){
          console.log(error)
        }


      })
     

    })

    //alert close and showing error
    $("#AtttoCardError a").click(function(){
      $("#AtttoCardError").hide()
    })


    // after click buy product

    $("#buyproduct").click(function(){
      var dataId = $(this).attr('data-id')
      var intdataId = parseInt(dataId)
      // console.log(intdataId)
      var qty = $("#quantity").val()
      var qty =  parseInt(qty)

      // console.log(qty)

      

      var url = "{% url 'frontend:buy-product' 24  %}" 
      var csrfmiddlewaretoken = $("input[name=csrfmiddlewaretoken]").val()
      mydata = {csrfmiddlewaretoken:csrfmiddlewaretoken, productid:intdataId,quantity:qty}

      


      $.ajax({
        method:'POST',
        url:url,
        data:mydata,

        success:function(response){
          console.log(response)
          if(response.count ===1 ){
              var currentCount = $("#navbarCount").html()
              var intcurrentCount = parseInt(currentCount)
              console.log(intcurrentCount)
              $("#navbarCount").html(intcurrentCount + response.count)
              
              
          }
          //if not login
          if(response.error == "Login First"){
             alert("You need to Login First to apply order")
              $("#AtttoCardError p").html("You need to login first")
              $("#AtttoCardError").show()
              
              
          }

          //if customer is not in the db
          if(response.error == "Not a Customer"){
              $("#AtttoCardError p").html("Not a customer")
              $("#AtttoCardError").show()
              alert("The requested user is not in the customer list")
              
          }
          if(response.data == "Qty Updated"){
            $("#AtttoCardError p").html("Qty Updated")
            $("#AtttoCardError").show()
             alert("Qty updated")
             
         }

          
          
        },
        error:function(error){
          console.log(error)
        }


      })
     
    })
     
  </script>


    
{% endblock javascripts %}
    